#ifndef OD_H
#define OD_H


// THIS FILE IS GENERATED AUTOMATICALLY!
// DO NOT EDIT THIS FILE!


// user code begin

// user code end

// Counters of OD objects
#define OD_CNT_NMT 1
#define OD_CNT_EM 1
#define OD_CNT_SYNC 1
#define OD_CNT_SYNC_PROD 1
#define OD_CNT_STORAGE 1
#define OD_CNT_TIME 1
#define OD_CNT_EM_PROD 1
#define OD_CNT_HB_CONS 1
#define OD_CNT_HB_PROD 1
#define OD_CNT_SDO_SRV 1
#define OD_CNT_SDO_CLI 1
#define OD_CNT_RPDO 4
#define OD_CNT_TPDO 4


// Sizes of OD arrays
#define OD_CNT_ARR_1003 16
#define OD_CNT_ARR_1010 4
#define OD_CNT_ARR_1011 4
#define OD_CNT_ARR_1016 8


#ifndef OD_ATTR_OD
#define OD_ATTR_OD
#endif
extern OD_ATTR_OD OD_t *OD;


// Object dictionary entries - shortcuts
#define OD_ENTRY_H1000 &OD->list[0]
#define OD_ENTRY_H1001 &OD->list[1]
#define OD_ENTRY_H1003 &OD->list[2]
#define OD_ENTRY_H1005 &OD->list[3]
#define OD_ENTRY_H1006 &OD->list[4]
#define OD_ENTRY_H1007 &OD->list[5]
#define OD_ENTRY_H1010 &OD->list[6]
#define OD_ENTRY_H1011 &OD->list[7]
#define OD_ENTRY_H1012 &OD->list[8]
#define OD_ENTRY_H1014 &OD->list[9]
#define OD_ENTRY_H1015 &OD->list[10]
#define OD_ENTRY_H1016 &OD->list[11]
#define OD_ENTRY_H1017 &OD->list[12]
#define OD_ENTRY_H1018 &OD->list[13]
#define OD_ENTRY_H1019 &OD->list[14]
#define OD_ENTRY_H1200 &OD->list[15]
#define OD_ENTRY_H1280 &OD->list[16]
#define OD_ENTRY_H1400 &OD->list[17]
#define OD_ENTRY_H1401 &OD->list[18]
#define OD_ENTRY_H1402 &OD->list[19]
#define OD_ENTRY_H1403 &OD->list[20]
#define OD_ENTRY_H1600 &OD->list[21]
#define OD_ENTRY_H1601 &OD->list[22]
#define OD_ENTRY_H1602 &OD->list[23]
#define OD_ENTRY_H1603 &OD->list[24]
#define OD_ENTRY_H1800 &OD->list[25]
#define OD_ENTRY_H1801 &OD->list[26]
#define OD_ENTRY_H1802 &OD->list[27]
#define OD_ENTRY_H1803 &OD->list[28]
#define OD_ENTRY_H1A00 &OD->list[29]
#define OD_ENTRY_H1A01 &OD->list[30]
#define OD_ENTRY_H1A02 &OD->list[31]
#define OD_ENTRY_H1A03 &OD->list[32]
#define OD_ENTRY_H2000 &OD->list[33]
#define OD_ENTRY_H2050 &OD->list[34]
#define OD_ENTRY_H2100 &OD->list[35]
#define OD_ENTRY_H2300 &OD->list[36]
#define OD_ENTRY_H2400 &OD->list[37]
#define OD_ENTRY_H2500 &OD->list[38]
#define OD_ENTRY_H2600 &OD->list[39]
#define OD_ENTRY_H2700 &OD->list[40]
#define OD_ENTRY_H2800 &OD->list[41]
#define OD_ENTRY_H2900 &OD->list[42]
#define OD_ENTRY_H3000 &OD->list[43]
#define OD_ENTRY_H3100 &OD->list[44]
#define OD_ENTRY_H3200 &OD->list[45]


// Object dictionary entries - shortcuts with names
#define OD_ENTRY_H1000_deviceType &OD->list[0]
#define OD_ENTRY_H1001_errorRegister &OD->list[1]
#define OD_ENTRY_H1003_pre_definedErrorField &OD->list[2]
#define OD_ENTRY_H1005_COB_ID_SYNCMessage &OD->list[3]
#define OD_ENTRY_H1006_communicationCyclePeriod &OD->list[4]
#define OD_ENTRY_H1007_synchronousWindowLength &OD->list[5]
#define OD_ENTRY_H1010_storeParameters &OD->list[6]
#define OD_ENTRY_H1011_restoreDefaultParameters &OD->list[7]
#define OD_ENTRY_H1012_COB_IDTimeStampObject &OD->list[8]
#define OD_ENTRY_H1014_COB_ID_EMCY &OD->list[9]
#define OD_ENTRY_H1015_inhibitTimeEMCY &OD->list[10]
#define OD_ENTRY_H1016_consumerHeartbeatTime &OD->list[11]
#define OD_ENTRY_H1017_producerHeartbeatTime &OD->list[12]
#define OD_ENTRY_H1018_identity &OD->list[13]
#define OD_ENTRY_H1019_synchronousCounterOverflowValue &OD->list[14]
#define OD_ENTRY_H1200_SDOServerParameter &OD->list[15]
#define OD_ENTRY_H1280_SDOClientParameter &OD->list[16]
#define OD_ENTRY_H1400_RPDOCommunicationParameter &OD->list[17]
#define OD_ENTRY_H1401_RPDOCommunicationParameter &OD->list[18]
#define OD_ENTRY_H1402_RPDOCommunicationParameter &OD->list[19]
#define OD_ENTRY_H1403_RPDOCommunicationParameter &OD->list[20]
#define OD_ENTRY_H1600_RPDOMappingParameter &OD->list[21]
#define OD_ENTRY_H1601_RPDOMappingParameter &OD->list[22]
#define OD_ENTRY_H1602_RPDOMappingParameter &OD->list[23]
#define OD_ENTRY_H1603_RPDOMappingParameter &OD->list[24]
#define OD_ENTRY_H1800_TPDOCommunicationParameter &OD->list[25]
#define OD_ENTRY_H1801_TPDOCommunicationParameter &OD->list[26]
#define OD_ENTRY_H1802_TPDOCommunicationParameter &OD->list[27]
#define OD_ENTRY_H1803_TPDOCommunicationParameter &OD->list[28]
#define OD_ENTRY_H1A00_TPDOMappingParameter &OD->list[29]
#define OD_ENTRY_H1A01_TPDOMappingParameter &OD->list[30]
#define OD_ENTRY_H1A02_TPDOMappingParameter &OD->list[31]
#define OD_ENTRY_H1A03_TPDOMappingParameter &OD->list[32]
#define OD_ENTRY_H2000_conf &OD->list[33]
#define OD_ENTRY_H2050_sysTime &OD->list[34]
#define OD_ENTRY_H2100_motor &OD->list[35]
#define OD_ENTRY_H2300_adc &OD->list[36]
#define OD_ENTRY_H2400_meas &OD->list[37]
#define OD_ENTRY_H2500_model &OD->list[38]
#define OD_ENTRY_H2600_phaseAmpl &OD->list[39]
#define OD_ENTRY_H2700_lineFreq &OD->list[40]
#define OD_ENTRY_H2800_armFreq &OD->list[41]
#define OD_ENTRY_H2900_rms &OD->list[42]
#define OD_ENTRY_H3000_mean &OD->list[43]
#define OD_ENTRY_H3100_power &OD->list[44]
#define OD_ENTRY_H3200_powerFactor &OD->list[45]


// OD config structure
#ifdef CO_MULTIPLE_OD
#define OD_INIT_CONFIG(config) {\
(config).CNT_NMT = OD_CNT_NMT;\
(config).ENTRY_H1017 = OD_ENTRY_H1017_producerHeartbeatTime;\
(config).CNT_HB_CONS = OD_CNT_HB_CONS;\
(config).CNT_ARR_1016 = OD_CNT_ARR_1016;\
(config).ENTRY_H1016 = OD_ENTRY_H1016_consumerHeartbeatTime;\
(config).CNT_EM = OD_CNT_EM;\
(config).ENTRY_H1001 = OD_ENTRY_H1001_errorRegister;\
(config).ENTRY_H1014 = OD_ENTRY_H1014_COB_ID_EMCY;\
(config).ENTRY_H1015 = OD_ENTRY_H1015_inhibitTimeEMCY;\
(config).CNT_ARR_1003 = OD_CNT_ARR_1003;\
(config).ENTRY_H1003 = OD_ENTRY_H1003_pre_definedErrorField;\
(config).CNT_SDO_SRV = OD_CNT_SDO_SRV;\
(config).ENTRY_H1200 = OD_ENTRY_H1200_SDOServerParameter;\
(config).CNT_SDO_CLI = OD_CNT_SDO_CLI;\
(config).ENTRY_H1280 = OD_ENTRY_H1280_SDOClientParameter;\
(config).CNT_TIME = OD_CNT_TIME;\
(config).ENTRY_H1012 = OD_ENTRY_H1012_COB_IDTimeStampObject;\
(config).CNT_SYNC = OD_CNT_SYNC;\
(config).ENTRY_H1005 = OD_ENTRY_H1005_COB_ID_SYNCMessage;\
(config).ENTRY_H1006 = OD_ENTRY_H1006_communicationCyclePeriod;\
(config).ENTRY_H1007 = OD_ENTRY_H1007_synchronousWindowLength;\
(config).ENTRY_H1019 = OD_ENTRY_H1019_synchronousCounterOverflowValue;\
(config).CNT_RPDO = OD_CNT_RPDO;\
(config).ENTRY_H1400 = OD_ENTRY_H1400_RPDOCommunicationParameter;\
(config).ENTRY_H1600 = OD_ENTRY_H1600_RPDOMappingParameter;\
(config).CNT_TPDO = OD_CNT_TPDO;\
(config).ENTRY_H1800 = OD_ENTRY_H1800_TPDOCommunicationParameter;\
(config).ENTRY_H1A00 = OD_ENTRY_H1A00_TPDOMappingParameter;\
(config).CNT_LEDS = 0;\
(config).CNT_GFC = 0;\
(config).ENTRY_H1300 = NULL;\
(config).CNT_SRDO = 0;\
(config).ENTRY_H1301 = NULL;\
(config).ENTRY_H1381 = NULL;\
(config).ENTRY_H13FE = NULL;\
(config).ENTRY_H13FF = NULL;\
(config).CNT_LSS_SLV = 0;\
(config).CNT_LSS_MST = 0;\
(config).CNT_GTWA = 0;\
(config).CNT_TRACE = 0;\
}
#endif

#endif /* OD_H */
