#include <regs_data.h>


// THIS FILE IS GENERATED AUTOMATICALLY!
// DO NOT EDIT THIS FILE!


// user code begin

// user code end

struct _S_regs_data regs_data = {
.deviceType = {
    .value = 0 /*  */
},
.errorRegister = {
    .value = 0 /*  */
},
.pre_definedErrorField = {
    .numberOfErrors = 0 /* Number of sub-entries */,
    .pre_definedErrorField = { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 } /*  */
},
.COB_ID_SYNCMessage = {
    .value = 0x80 /*  */
},
.communicationCyclePeriod = {
    .value = 0 /*  */
},
.synchronousWindowLength = {
    .value = 0 /*  */
},
.storeParameters = {
    .highestSub_indexSupported = 4 /* Number of sub-entries */,
    .storeParameters = { 1, 1, 1, 1 } /*  */
},
.restoreDefaultParameters = {
    .highestSub_indexSupported = 4 /* Number of sub-entries */,
    .restoreDefaultParameters = { 1, 1, 1, 1 } /*  */
},
.COB_IDTimeStampObject = {
    .value = 0x00000100 /*  */
},
.COB_ID_EMCY = {
    .value = 0x80 /*  */
},
.inhibitTimeEMCY = {
    .value = 0 /*  */
},
.consumerHeartbeatTime = {
    .highestSub_indexSupported = 8 /* Number of sub-entries */,
    .consumerHeartbeatTime = { 0, 0, 0, 0, 0, 0, 0, 0 } /*  */
},
.producerHeartbeatTime = {
    .value = 0 /*  */
},
.identity = {
    .highestSub_indexSupported = 4 /* Number of sub-entries */,
    .vendor_id = 0 /*  */,
    .productCode = 0 /*  */,
    .revisionNumber = 0 /*  */,
    .serialNumber = 0 /*  */
},
.synchronousCounterOverflowValue = {
    .value = 0 /*  */
},
.SDOServerParameter = {
    .highestSub_indexSupported = 2 /* Number of sub-entries */,
    .COB_IDClientToServer_rx_ = 0x600 /*  */,
    .COB_IDServerToClient_tx_ = 0x580 /*  */
},
.SDOClientParameter = {
    .count = 3 /* Number of sub-entries */,
    .COB_IDClientToServer_tx_ = 0x80000000 /*  */,
    .COB_IDServerToClient_rx_ = 0x80000000 /*  */,
    .node_idOfTheSDOServer = 1 /*  */
},
.RPDOCommunicationParameter = {
    .highestSub_indexSupported = 5 /* Number of sub-entries */,
    .COB_IDUsedByRPDO = 0x80000200 /*  */,
    .transmissionType = 254 /*  */,
    .eventTimer = 0 /*  */
},
.RPDOCommunicationParameter_1401 = {
    .highestSub_indexSupported = 5 /* Number of sub-entries */,
    .COB_IDUsedByRPDO = 0x80000300 /*  */,
    .transmissionType = 254 /*  */,
    .eventTimer = 0 /*  */
},
.RPDOCommunicationParameter_1402 = {
    .highestSub_indexSupported = 5 /* Number of sub-entries */,
    .COB_IDUsedByRPDO = 0x80000400 /*  */,
    .transmissionType = 254 /*  */,
    .eventTimer = 0 /*  */
},
.RPDOCommunicationParameter_1403 = {
    .highestSub_indexSupported = 5 /* Number of sub-entries */,
    .COB_IDUsedByRPDO = 0x80000500 /*  */,
    .transmissionType = 254 /*  */,
    .eventTimer = 0 /*  */
},
.RPDOMappingParameter = {
    .numberOfMappedApplicationObjectsInPDO = 0 /* Number of sub-entries */,
    .applicationObject1 = 0 /*  */,
    .applicationObject2 = 0 /*  */,
    .applicationObject3 = 0 /*  */,
    .applicationObject4 = 0 /*  */,
    .applicationObject5 = 0 /*  */,
    .applicationObject6 = 0 /*  */,
    .applicationObject7 = 0 /*  */,
    .applicationObject8 = 0 /*  */
},
.RPDOMappingParameter_1601 = {
    .numberOfMappedApplicationObjectsInPDO = 0 /* Number of sub-entries */,
    .applicationObject1 = 0 /*  */,
    .applicationObject2 = 0 /*  */,
    .applicationObject3 = 0 /*  */,
    .applicationObject4 = 0 /*  */,
    .applicationObject5 = 0 /*  */,
    .applicationObject6 = 0 /*  */,
    .applicationObject7 = 0 /*  */,
    .applicationObject8 = 0 /*  */
},
.RPDOMappingParameter_1602 = {
    .numberOfMappedApplicationObjectsInPDO = 0 /* Number of sub-entries */,
    .applicationObject1 = 0 /*  */,
    .applicationObject2 = 0 /*  */,
    .applicationObject3 = 0 /*  */,
    .applicationObject4 = 0 /*  */,
    .applicationObject5 = 0 /*  */,
    .applicationObject6 = 0 /*  */,
    .applicationObject7 = 0 /*  */,
    .applicationObject8 = 0 /*  */
},
.RPDOMappingParameter_1603 = {
    .numberOfMappedApplicationObjectsInPDO = 0 /* Number of sub-entries */,
    .applicationObject1 = 0 /*  */,
    .applicationObject2 = 0 /*  */,
    .applicationObject3 = 0 /*  */,
    .applicationObject4 = 0 /*  */,
    .applicationObject5 = 0 /*  */,
    .applicationObject6 = 0 /*  */,
    .applicationObject7 = 0 /*  */,
    .applicationObject8 = 0 /*  */
},
.TPDOCommunicationParameter = {
    .highestSub_indexSupported = 6 /* Number of sub-entries */,
    .COB_IDUsedByTPDO = 0xC0000180 /*  */,
    .transmissionType = 254 /*  */,
    .inhibitTime = 0 /*  */,
    .eventTimer = 0 /*  */,
    .SYNCStartValue = 0 /*  */
},
.TPDOCommunicationParameter_1801 = {
    .highestSub_indexSupported = 6 /* Number of sub-entries */,
    .COB_IDUsedByTPDO = 0xC0000280 /*  */,
    .transmissionType = 254 /*  */,
    .inhibitTime = 0 /*  */,
    .eventTimer = 0 /*  */,
    .SYNCStartValue = 0 /*  */
},
.TPDOCommunicationParameter_1802 = {
    .highestSub_indexSupported = 6 /* Number of sub-entries */,
    .COB_IDUsedByTPDO = 0xC0000380 /*  */,
    .transmissionType = 254 /*  */,
    .inhibitTime = 0 /*  */,
    .eventTimer = 0 /*  */,
    .SYNCStartValue = 0 /*  */
},
.TPDOCommunicationParameter_1803 = {
    .highestSub_indexSupported = 6 /* Number of sub-entries */,
    .COB_IDUsedByTPDO = 0xC0000480 /*  */,
    .transmissionType = 254 /*  */,
    .inhibitTime = 0 /*  */,
    .eventTimer = 0 /*  */,
    .SYNCStartValue = 0 /*  */
},
.TPDOMappingParameter = {
    .numberOfMappedApplicationObjectsInPDO = 0 /* Number of sub-entries */,
    .applicationObject1 = 0 /*  */,
    .applicationObject2 = 0 /*  */,
    .applicationObject3 = 0 /*  */,
    .applicationObject4 = 0 /*  */,
    .applicationObject5 = 0 /*  */,
    .applicationObject6 = 0 /*  */,
    .applicationObject7 = 0 /*  */,
    .applicationObject8 = 0 /*  */
},
.TPDOMappingParameter_1a01 = {
    .numberOfMappedApplicationObjectsInPDO = 0 /* Number of sub-entries */,
    .applicationObject1 = 0 /*  */,
    .applicationObject2 = 0 /*  */,
    .applicationObject3 = 0 /*  */,
    .applicationObject4 = 0 /*  */,
    .applicationObject5 = 0 /*  */,
    .applicationObject6 = 0 /*  */,
    .applicationObject7 = 0 /*  */,
    .applicationObject8 = 0 /*  */
},
.TPDOMappingParameter_1a02 = {
    .numberOfMappedApplicationObjectsInPDO = 0 /* Number of sub-entries */,
    .applicationObject1 = 0 /*  */,
    .applicationObject2 = 0 /*  */,
    .applicationObject3 = 0 /*  */,
    .applicationObject4 = 0 /*  */,
    .applicationObject5 = 0 /*  */,
    .applicationObject6 = 0 /*  */,
    .applicationObject7 = 0 /*  */,
    .applicationObject8 = 0 /*  */
},
.TPDOMappingParameter_1a03 = {
    .numberOfMappedApplicationObjectsInPDO = 0 /* Number of sub-entries */,
    .applicationObject1 = 0 /*  */,
    .applicationObject2 = 0 /*  */,
    .applicationObject3 = 0 /*  */,
    .applicationObject4 = 0 /*  */,
    .applicationObject5 = 0 /*  */,
    .applicationObject6 = 0 /*  */,
    .applicationObject7 = 0 /*  */,
    .applicationObject8 = 0 /*  */
},
.conf = {
    .count = 3 /*  */
},
.sysTime = {
    .count = 3 /*  */
},
.motor = {
    .count = 7 /*  */
},
.adc = {
    .count = 12 /*  */
},
.meas = {
    .count = 18 /*  */
},
.model = {
    .count = 20 /*  */
},
.phaseAmpl = {
    .count = 6 /*  */
},
.lineFreq = {
    .count = 15 /*  */
},
.armFreq = {
    .count = 6 /*  */
},
.rms = {
    .count = 15 /*  */
},
.mean = {
    .count = 9 /*  */
},
.power = {
    .count = 9 /*  */
},
.powerFactor = {
    .count = 3 /*  */
}
};
