#ifndef REG_IDS_H
#define REG_IDS_H


// THIS FILE IS GENERATED AUTOMATICALLY!
// DO NOT EDIT THIS FILE!

// Modules for registers

// Begin

// Conf
// Nominal values
#define REG_ID_CONF_U_NOM    0
#define REG_ID_CONF_I_NOM    1
#define REG_ID_CONF_F_NOM    2

// Motor
// Nominal values
#define REG_ID_MOTOR_F_NOM    50
// Nominal stator values
#define REG_ID_MOTOR_S_U_NOM    51
#define REG_ID_MOTOR_S_I_NOM    52
// Nominal rotor values
#define REG_ID_MOTOR_U_NOM    53
#define REG_ID_MOTOR_I_NOM    54


// SysTime
#define REG_ID_SYS_TIME_COUNTER_MS    200
#define REG_ID_SYS_TIME_COUNTER_S    201
#define REG_ID_SYS_TIME_RUN_COUNTER_S    202

// ADC
// Phases voltage
// Raw
#define REG_ID_ADC_UA_RAW    300
#define REG_ID_ADC_UB_RAW    301
#define REG_ID_ADC_UC_RAW    302
// Rel
#define REG_ID_ADC_UA    303
#define REG_ID_ADC_UB    304
#define REG_ID_ADC_UC    305
// Calibration
#define REG_ID_ADC_UA_GAIN    306
#define REG_ID_ADC_UA_OFFSET    307
#define REG_ID_ADC_UB_GAIN    308
#define REG_ID_ADC_UB_OFFSET    309
#define REG_ID_ADC_UC_GAIN    310
#define REG_ID_ADC_UC_OFFSET    311

// Measurement
#define REG_ID_MEAS_UA    500
#define REG_ID_MEAS_UB    501
#define REG_ID_MEAS_UC    502
#define REG_ID_MEAS_IA    503
#define REG_ID_MEAS_IB    504
#define REG_ID_MEAS_IC    505
#define REG_ID_MEAS_UARM    506
#define REG_ID_MEAS_IARM    507
#define REG_ID_MEAS_CELL_UA    508
#define REG_ID_MEAS_CELL_UB    509
#define REG_ID_MEAS_CELL_UC    510
#define REG_ID_MEAS_CELL_IA    511
#define REG_ID_MEAS_CELL_IB    512
#define REG_ID_MEAS_CELL_IC    513

// Model
#define REG_ID_MODEL_STATOR_UA    700
#define REG_ID_MODEL_STATOR_UB    701
#define REG_ID_MODEL_STATOR_UC    702
#define REG_ID_MODEL_STATOR_IA    703
#define REG_ID_MODEL_STATOR_IB    704
#define REG_ID_MODEL_STATOR_IC    705
#define REG_ID_MODEL_ROTOR_U    706
#define REG_ID_MODEL_ROTOR_I    707
#define REG_ID_MODEL_R_START_I    708
#define REG_ID_MODEL_MOTOR_M    709
#define REG_ID_MODEL_MOTOR_W    710
#define REG_ID_MODEL_RECTIFIER_UA    711
#define REG_ID_MODEL_RECTIFIER_UB    712
#define REG_ID_MODEL_RECTIFIER_UC    713
#define REG_ID_MODEL_RECTIFIER_IA    714
#define REG_ID_MODEL_RECTIFIER_IB    715
#define REG_ID_MODEL_RECTIFIER_IC    716

// Phase and Amplitude.
#define REG_ID_PHASE_AMPL_UA_PHASE    1000
#define REG_ID_PHASE_AMPL_UA_AMPL    1001
#define REG_ID_PHASE_AMPL_UB_PHASE    1002
#define REG_ID_PHASE_AMPL_UB_AMPL    1003
#define REG_ID_PHASE_AMPL_UC_PHASE    1004
#define REG_ID_PHASE_AMPL_UC_AMPL    1005

#define REG_ID_LINE_FREQ_UA    1200
#define REG_ID_LINE_FREQ_UA_FILTER_T    1201
#define REG_ID_LINE_FREQ_UA_FILT    1202
#define REG_ID_LINE_FREQ_UB    1203
#define REG_ID_LINE_FREQ_UB_FILTER_T    1204
#define REG_ID_LINE_FREQ_UB_FILT    1205
#define REG_ID_LINE_FREQ_UC    1206
#define REG_ID_LINE_FREQ_UC_FILTER_T    1207
#define REG_ID_LINE_FREQ_UC_FILT    1208

#define REG_ID_RMS_UA    1400
#define REG_ID_RMS_UB    1401
#define REG_ID_RMS_UC    1402

#define REG_ID_MEAN_IARM    1500
#define REG_ID_MEAN_IARM_FILTER_T    1501
#define REG_ID_MEAN_IARM_FILT    1502
#define REG_ID_MEAN_UARM    1503
#define REG_ID_MEAN_UARM_FILTER_T    1504
#define REG_ID_MEAN_UARM_FILT    1505

// End

#endif /* REG_IDS_H */
