#ifndef REG_IDS_H
#define REG_IDS_H


// THIS FILE IS GENERATED AUTOMATICALLY!
// DO NOT EDIT THIS FILE!

// Modules for registers

// Begin

// Conf
// Nominal values
#define REG_ID_CONF_U_NOM    0
#define REG_ID_CONF_I_NOM    1


// ADC
// Phases voltage
// Raw
#define REG_ID_ADC_UA_RAW    200
#define REG_ID_ADC_UB_RAW    201
#define REG_ID_ADC_UC_RAW    202
// Rel
#define REG_ID_ADC_UA    203
#define REG_ID_ADC_UB    204
#define REG_ID_ADC_UC    205
// Calibration
#define REG_ID_ADC_UA_GAIN    206
#define REG_ID_ADC_UA_OFFSET    207
#define REG_ID_ADC_UB_GAIN    208
#define REG_ID_ADC_UB_OFFSET    209
#define REG_ID_ADC_UC_GAIN    210
#define REG_ID_ADC_UC_OFFSET    211


// End

#endif /* REG_IDS_H */
